import type { Metadata } from 'next'

//Components
import { Header } from '@/components/shared'

export const metadata: Metadata = {
  title: 'Next Pizza',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='min-h-screen'>
      <Header />
      {children}
    </div>
  )
}
