import { Container, Header } from '@/shared/components/shared'

export const metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by Next.js'
}

export default function CheckoutLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className='min-h-screen bg-[#f4f1ee]'>
      <Container>
        <Header hasSearch={false} hasCart={false} />
        {children}
      </Container>
    </div>
  )
}
